#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Get list of staged files
files=$(git diff --cached --name-only --diff-filter=ACM | grep -E "\.ts$|\.tsx$")

# Skip pre-commit for test files
if echo "$files" | grep -q "\.test\.ts$\|\.test\.tsx$"; then
  echo "Test files detected, skipping pre-commit hooks"
  exit 0
fi

cd frontend && npm run pre-commit
