"""API schemas package."""

from .auth import (
    Role,
    RoleCreate,
    RoleUpdate,
    Token,
    TokenData,
    User,
    UserCreate,
    UserInDB,
    UserUpdate,
)
from .process import (
    ApiResponse,
    PaginatedResponse,
    ProcessDefinitionBase,
    ProcessDefinitionCreate,
    ProcessDefinitionResponse,
    ProcessDefinitionUpdate,
    ProcessInstanceCreate,
    ProcessInstanceFilter,
    ProcessInstanceResponse,
    ProcessStats,
    ProcessVariableDefinition,
    ProcessVariableValidation,
    ProcessVariableValue,
    ScriptContent,
    ScriptResponse,
    TokenResponse,
)

__all__ = [
    # Auth schemas
    "Token",
    "TokenData",
    "User",
    "UserCreate",
    "UserUpdate",
    "Role",
    "RoleCreate",
    "RoleUpdate",
    "UserInDB",
    # Process schemas
    "ProcessVariableValue",
    "ProcessVariableValidation",
    "ProcessVariableDefinition",
    "ProcessDefinitionBase",
    "ProcessDefinitionCreate",
    "ProcessDefinitionUpdate",
    "ProcessDefinitionResponse",
    "PaginatedResponse",
    "ApiResponse",
    "ProcessInstanceCreate",
    "ProcessInstanceResponse",
    "ProcessInstanceFilter",
    "ProcessStats",
    "ScriptContent",
    "ScriptResponse",
    "TokenResponse",
]
